name: "Pull Request Labeler"
on:
  pull_request_target:
    types:
      - opened

jobs:
  triage:
    permissions:
      pull-requests: write
      
    runs-on: ubuntu-latest
    steps:
    - id: hello
      uses: AnuragThePathak/labeler@v1.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yaml
        sync-labels: false
    - name: Get level
      run: echo "The level is ${{ steps.hello.outputs.Level }}"

